import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Shield, Lock, Eye, Database, MessageSquare, Users } from "lucide-react";
import { NavigationControl } from "@/components/NavigationControl";

export default function PrivacyPolicy() {
  const [_, setLocation] = useLocation();
  const [userRole, setUserRole] = useState<string>("");
  
  useEffect(() => {
    const userStr = localStorage.getItem("vanops_user");
    if (userStr) {
      const user = JSON.parse(userStr);
      setUserRole(user.role || "");
    }
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-green-900 to-slate-900 p-4">
      <div className="max-w-3xl mx-auto space-y-3 py-4">
        <NavigationControl variant="back" fallbackRoute="/" />

        {/* Header */}
        <Card className="bg-gradient-to-br from-green-600 to-emerald-700 border-none text-white">
          <CardContent className="p-6">
            <div className="flex items-center gap-3">
              <div className="bg-white/20 rounded-full p-3">
                <Shield className="h-8 w-8" />
              </div>
              <div>
                <h1 className="text-3xl font-bold">Privacy Policy</h1>
                <p className="text-sm text-green-100">Lot Ops Pro - Your privacy matters</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Last Updated */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardContent className="p-3">
            <div className="space-y-2">
              <p className="text-white text-xs">
                <strong>Last Updated:</strong> November 21, 2025
              </p>
              <p className="text-white text-xs leading-relaxed">
                This Privacy Policy governs the collection, use, and protection of data within 
                Lot Ops Pro, an internal operations management system for Manheim Nashville. 
                By using this application, you agree to the terms outlined below.
              </p>
              <p className="text-slate-300 text-[10px] italic">
                Note: This policy is designed for internal enterprise use and operational compliance. 
                Legal review recommended before commercial deployment.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Scope of Policy */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Shield className="h-5 w-5 text-blue-400" />
              Scope of This Policy
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-2 p-3 pt-0">
            <p className="text-sm leading-snug">This Privacy Policy applies to:</p>
            <ul className="text-sm space-y-1 ml-4 list-disc">
              <li>All employees using Lot Ops Pro (drivers, supervisors, management)</li>
              <li>Communications sent through the in-app messaging system</li>
              <li>Operational data collected during lot management activities</li>
              <li>Corporate information shared within the application</li>
              <li>Performance metrics and analytics generated by the system</li>
            </ul>
          </CardContent>
        </Card>

        {/* Message Privacy - Core Feature */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Lock className="h-5 w-5 text-green-400" />
              Message Privacy - Private by Default
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <div className="bg-green-900/30 rounded p-3 border border-green-500/30">
              <p className="text-sm font-semibold mb-2">🔒 All Messages Are Private Unless Marked Official</p>
              <p className="text-sm leading-snug">
                Lot Ops Pro is built with privacy as the default setting. Every message you send is 
                <span className="font-bold text-green-200"> private </span> 
                unless you explicitly toggle it as "Official Message."
              </p>
            </div>

            <div className="space-y-2">
              <p className="text-sm font-semibold text-green-300">What This Means:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Private messages are visible ONLY to you and the person you're messaging</li>
                <li>Developers cannot see private messages (system blocks access)</li>
                <li>Supervisors see only Official messages + their own private conversations</li>
                <li>Operations Manager sees Official messages + their scope of communications</li>
              </ul>
            </div>

            <div className="bg-amber-900/30 rounded p-3 border border-amber-500/30">
              <p className="text-sm font-semibold mb-1">📋 Official Messages</p>
              <p className="text-sm leading-snug">
                Messages marked as "Official" are logged for operational purposes. These include:
              </p>
              <ul className="text-xs space-y-1 ml-4 list-disc mt-2">
                <li>Safety incidents and reporting</li>
                <li>Lot assignments and work orders</li>
                <li>Company announcements</li>
                <li>Performance documentation</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Developer Lockout */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Eye className="h-5 w-5 text-red-400" />
              Developer Access - Locked Out by Design
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <p className="text-sm leading-snug">
              The Developer role (Jason and future developers) is <span className="font-bold text-red-300">blocked from accessing private messages</span>. 
              This isn't just a policy - it's built into the system code.
            </p>
            
            <div className="bg-red-900/30 rounded p-3 border border-red-500/30">
              <p className="text-sm font-semibold mb-2">What Developers CAN See:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Official messages only (company business)</li>
                <li>System performance metrics</li>
                <li>App usage statistics (anonymized)</li>
              </ul>
            </div>

            <div className="bg-green-900/30 rounded p-3 border border-green-500/30">
              <p className="text-sm font-semibold mb-2">What Developers CANNOT See:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Your private conversations</li>
                <li>Personal messages between drivers</li>
                <li>Any communication not marked "Official"</li>
              </ul>
            </div>

            <p className="text-xs italic text-slate-300">
              You can verify this yourself in Demo Mode - log in as Developer and try to access messages. 
              You'll get "Access Denied" on all private communications.
            </p>
          </CardContent>
        </Card>

        {/* Data Collection */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Database className="h-5 w-5 text-blue-400" />
              What Data We Collect
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <div className="space-y-2">
              <p className="text-sm font-semibold text-blue-300">Operational Data (Required for App Function):</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Employee name and badge number</li>
                <li>Vehicle scan data (VIN, lot codes, locations)</li>
                <li>GPS coordinates for routing</li>
                <li>Shift times and performance metrics</li>
                <li>Official messages for business operations</li>
              </ul>
            </div>

            <div className="space-y-2">
              <p className="text-sm font-semibold text-slate-300">What We DO NOT Collect:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Personal phone numbers (only last 4 digits for driver ID)</li>
                <li>Private message content (not stored long-term)</li>
                <li>Location data outside work hours</li>
                <li>Any data unrelated to lot operations</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Data Storage & Security */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Shield className="h-5 w-5 text-purple-400" />
              Data Storage & Security
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <ul className="text-sm space-y-2">
              <li className="flex gap-2">
                <span>✓</span>
                <span>All data stored in secure PostgreSQL database (Neon serverless)</span>
              </li>
              <li className="flex gap-2">
                <span>✓</span>
                <span>Private messages auto-deleted after 30 days (configurable)</span>
              </li>
              <li className="flex gap-2">
                <span>✓</span>
                <span>Official messages retained for operational/safety purposes</span>
              </li>
              <li className="flex gap-2">
                <span>✓</span>
                <span>PIN-based authentication for secure access</span>
              </li>
              <li className="flex gap-2">
                <span>✓</span>
                <span>Role-based permissions (drivers, supervisors, operations manager)</span>
              </li>
            </ul>
          </CardContent>
        </Card>

        {/* User Rights */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Users className="h-5 w-5 text-yellow-400" />
              Your Rights
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <p className="text-sm leading-snug">As a Lot Ops Pro user, you have the right to:</p>
            <ul className="text-sm space-y-2 ml-4 list-disc">
              <li>Request access to your operational data</li>
              <li>Request deletion of non-essential data</li>
              <li>Export your message history (Official messages only)</li>
              <li>Opt out of non-essential features</li>
              <li>Know who has access to your data</li>
            </ul>
            <p className="text-xs text-slate-300 mt-3">
              To exercise these rights, contact your supervisor or operations manager.
            </p>
          </CardContent>
        </Card>

        {/* Safety Disclaimer */}
        <Card className="bg-gradient-to-br from-red-600 to-orange-700 border-none text-white">
          <CardContent className="p-4">
            <div className="flex items-start gap-3">
              <MessageSquare className="h-6 w-6 flex-shrink-0 mt-1" />
              <div>
                <h3 className="font-bold text-lg mb-1">Safety First</h3>
                <p className="text-sm leading-snug">
                  DO NOT use messaging features while operating vehicles. Pull over and park safely 
                  before sending or reading messages. Voice text coming in Version 2.0.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Corporate Data Security */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Database className="h-5 w-5 text-indigo-400" />
              Corporate Information Security
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <p className="text-sm leading-snug">
              Any corporate or sensitive business information shared within Lot Ops Pro is protected by:
            </p>
            <ul className="text-sm space-y-2 ml-4 list-disc">
              <li><strong>Role-Based Access Control:</strong> Users only see information relevant to their role (supervisor, driver, ops manager)</li>
              <li><strong>Encrypted Storage:</strong> All data stored in PostgreSQL database (Neon serverless with encryption at rest)</li>
              <li><strong>System Logs:</strong> Basic activity logging for debugging and support purposes</li>
              <li><strong>Access Restrictions:</strong> Temporary employees blocked from corporate resources (Settings, Help, Company Resources)</li>
              <li><strong>Session Management:</strong> 12-hour secure sessions with automatic logout</li>
            </ul>
            <div className="bg-indigo-900/30 rounded p-3 border border-indigo-500/30 mt-2">
              <p className="text-xs leading-snug">
                <strong>Corporate Data Includes:</strong> Company resources, safety materials, employee rosters, 
                performance reports, operational analytics, and management communications.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Data Retention */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Database className="h-5 w-5 text-orange-400" />
              Data Retention & Deletion
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <div className="space-y-2">
              <p className="text-sm font-semibold text-orange-300">What We Keep:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Official messages: Retained indefinitely for operational/safety purposes</li>
                <li>Performance data: Retained for review cycles and analytics</li>
                <li>Vehicle scan logs: Retained for operational tracking</li>
                <li>Safety incidents: Retained permanently for compliance</li>
                <li>Employee records: Retained per HR policy</li>
              </ul>
            </div>

            <div className="space-y-2">
              <p className="text-sm font-semibold text-green-300">Privacy Protections:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Private messages: Not accessible by developers (system-enforced)</li>
                <li>GPS data: Only collected during work hours for routing</li>
                <li>Temporary employee data: Access restricted to operational needs only</li>
                <li>Demo mode data: Session-based storage (not permanently saved)</li>
              </ul>
              <p className="text-xs text-slate-300 mt-2">
                <strong>Future Enhancement:</strong> Auto-deletion of old private messages planned for Version 2.0.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Third-Party Services */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Shield className="h-5 w-5 text-cyan-400" />
              Third-Party Services
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <p className="text-sm leading-snug">
              Lot Ops Pro uses the following third-party services to provide functionality:
            </p>
            <ul className="text-sm space-y-2 ml-4">
              <li className="flex gap-2">
                <span className="font-mono text-xs bg-slate-800 px-2 py-0.5 rounded">Neon</span>
                <span>PostgreSQL database hosting (data storage)</span>
              </li>
              <li className="flex gap-2">
                <span className="font-mono text-xs bg-slate-800 px-2 py-0.5 rounded">Replit</span>
                <span>Application hosting and development platform</span>
              </li>
              <li className="flex gap-2">
                <span className="font-mono text-xs bg-slate-800 px-2 py-0.5 rounded">Open-Meteo</span>
                <span>Weather data API (no personal data shared)</span>
              </li>
            </ul>
            <p className="text-xs text-slate-300 mt-2">
              These services have their own privacy policies. No personal messages or sensitive 
              employee data is shared with third parties beyond what's required for basic operation.
            </p>
          </CardContent>
        </Card>

        {/* Employee Rights & Responsibilities */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Users className="h-5 w-5 text-yellow-400" />
              Employee Rights & Responsibilities
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <div className="space-y-2">
              <p className="text-sm font-semibold text-yellow-300">Your Rights:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Access to your operational data and performance metrics</li>
                <li>Request deletion of non-essential personal data</li>
                <li>Export your Official message history</li>
                <li>Report privacy concerns to management</li>
                <li>Know who has access to your data</li>
              </ul>
            </div>

            <div className="space-y-2">
              <p className="text-sm font-semibold text-red-300">Your Responsibilities:</p>
              <ul className="text-sm space-y-1 ml-4 list-disc">
                <li>Use messaging system professionally and appropriately</li>
                <li>Protect your PIN and do not share login credentials</li>
                <li>Mark safety incidents and company business as "Official"</li>
                <li>Do not text while driving - safety first always</li>
                <li>Report security concerns or suspicious activity</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Legal Compliance */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardHeader className="pb-2 pt-3 px-3">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Shield className="h-5 w-5 text-purple-400" />
              Legal Compliance & Disclaimers
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white space-y-3 p-3 pt-0">
            <p className="text-sm leading-snug">
              <strong>Workplace Monitoring:</strong> As an internal operations tool, Lot Ops Pro collects 
              work-related data (GPS during work hours, performance metrics, official communications) for 
              legitimate business purposes. This is standard practice for operational management systems.
            </p>
            
            <p className="text-sm leading-snug">
              <strong>Data Disclosure:</strong> We may disclose data if required by law, legal process, 
              or in response to valid requests by public authorities (e.g., safety investigations, legal compliance).
            </p>

            <p className="text-sm leading-snug">
              <strong>Changes to Policy:</strong> This Privacy Policy may be updated to reflect changes in 
              functionality, legal requirements, or business practices. Users will be notified of significant changes.
            </p>

            <div className="bg-purple-900/30 rounded p-3 border border-purple-500/30 mt-2">
              <p className="text-xs leading-snug">
                <strong>Version 1.0 - Internal Use:</strong> This application is currently designed for internal use at Manheim Nashville. 
                The system architecture supports white-label deployment to other auction facilities with configurable lot layouts, 
                GPS coordinates, and organizational structures.
              </p>
              <p className="text-xs leading-snug mt-2">
                <strong>Future Commercial Deployment:</strong> If commercialized or deployed enterprise-wide, this privacy policy 
                will be reviewed and certified by qualified legal counsel to ensure full compliance with applicable federal, state, 
                and industry-specific regulations (including GDPR if applicable).
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Contact */}
        <Card className="bg-white/10 border-white/20 backdrop-blur-lg">
          <CardContent className="p-4">
            <p className="text-white text-sm font-semibold mb-2">
              Questions or Concerns?
            </p>
            <p className="text-white text-sm leading-snug">
              For privacy-related questions, data access requests, or security concerns, contact:
            </p>
            <ul className="text-white text-sm space-y-1 ml-4 list-disc mt-2">
              <li>Your direct supervisor for operational questions</li>
              <li>Operations Manager for data access requests</li>
              <li>HR Department for employee privacy concerns</li>
            </ul>
            <p className="text-slate-300 text-xs mt-3">
              This application is built with transparency and privacy as core principles. We are committed 
              to protecting your data and respecting your privacy while maintaining operational excellence.
            </p>
          </CardContent>
        </Card>

        {/* Footer */}
        <div className="text-center text-white/50 text-xs pb-4">
          <p>Dark Wave Studios © 2025</p>
          <p className="mt-1">Built for transparency, privacy, and operational excellence</p>
        </div>
      </div>
    </div>
  );
}
