import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Printer, Download, Send, TrendingUp, TrendingDown, Users, Package } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface QuarterlyReportProps {
  open: boolean;
  onClose: () => void;
}

interface ReportData {
  timestamp: string;
  reportTime: string;
  vanDrivers: Array<{
    driverNumber: string;
    name: string;
    role: string;
    mph: number;
    totalMoves: number;
    status: string;
  }>;
  inventoryDrivers: Array<{
    driverNumber: string;
    name: string;
    role: string;
    mph: number;
    totalMoves: number;
    status: string;
  }>;
  summary: {
    totalVanDrivers: number;
    totalInventoryDrivers: number;
    avgMPH: string;
    totalMoves: number;
  };
}

export function QuarterlyReport({ open, onClose }: QuarterlyReportProps) {
  const { toast } = useToast();
  const [isPrinting, setIsPrinting] = useState(false);

  const { data: reportData, isLoading, refetch } = useQuery<ReportData>({
    queryKey: ["/api/reports/quarterly"],
    enabled: open,
    refetchOnMount: true
  });

  const handlePrint = () => {
    setIsPrinting(true);
    setTimeout(() => {
      window.print();
      setIsPrinting(false);
    }, 100);
  };

  const handleDownload = () => {
    if (!reportData) return;

    const content = generateTextReport(reportData);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `quarterly-report-${reportData.reportTime}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast({ title: "Report Downloaded", description: "Report saved to your device" });
  };

  const handleSendToDrivers = async () => {
    // Send as broadcast message to all drivers
    if (!reportData) return;
    
    try {
      await fetch('/api/messages', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          fromId: 'Supervisor',
          toId: null, // Broadcast
          content: `📊 ${reportData.reportTime} Update - Avg MPH: ${reportData.summary.avgMPH} | Total Moves: ${reportData.summary.totalMoves}`,
          timestamp: new Date().toISOString(),
          isRead: false
        })
      });
      toast({ title: "Report Sent!", description: "All drivers notified via messaging system" });
    } catch (error) {
      toast({ title: "Send Failed", description: "Could not send to drivers", variant: "destructive" });
    }
  };

  const generateTextReport = (data: ReportData) => {
    let report = `===========================================\n`;
    report += `     QUARTERLY PERFORMANCE REPORT\n`;
    report += `     ${new Date().toLocaleDateString()} - ${data.reportTime}\n`;
    report += `===========================================\n\n`;
    
    report += `SUMMARY\n`;
    report += `-----------\n`;
    report += `Total Van Drivers: ${data.summary.totalVanDrivers}\n`;
    report += `Total Inventory Drivers: ${data.summary.totalInventoryDrivers}\n`;
    report += `Average MPH: ${data.summary.avgMPH}\n`;
    report += `Total Moves: ${data.summary.totalMoves}\n\n`;
    
    report += `VAN DRIVERS (Sorted by MPH)\n`;
    report += `-----------\n`;
    data.vanDrivers.forEach((d: any, i: number) => {
      report += `${i + 1}. ${d.name || `Driver ${d.driverNumber}`}\n`;
      report += `   MPH: ${d.mph.toFixed(1)} | Units: ${d.totalMoves}\n`;
    });
    
    report += `\n\nINVENTORY DRIVERS (Sorted by Units)\n`;
    report += `-----------\n`;
    data.inventoryDrivers.forEach((d: any, i: number) => {
      report += `${i + 1}. ${d.name || `Driver ${d.driverNumber}`}\n`;
      report += `   Units: ${d.totalMoves}\n`;
    });
    
    report += `\n===========================================\n`;
    report += `Generated by Lot Ops Pro\n`;
    
    return report;
  };

  if (isLoading) {
    return (
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-w-2xl">
          <div className="text-center py-12">
            <div className="text-slate-600">Loading report data...</div>
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  if (!reportData) return null;

  return (
    <>
      {/* Print Styles */}
      <style>{`
        @media print {
          body * {
            visibility: hidden;
          }
          #printable-report, #printable-report * {
            visibility: visible;
          }
          #printable-report {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>

      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader className="no-print">
            <DialogTitle className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-blue-600" />
              Quarterly Performance Report
            </DialogTitle>
          </DialogHeader>

          {/* Action Buttons */}
          <div className="flex gap-2 flex-wrap no-print">
            <Button onClick={handlePrint} className="flex items-center gap-2" data-testid="button-print-report">
              <Printer className="h-4 w-4" />
              Print Report
            </Button>
            <Button onClick={handleDownload} variant="outline" className="flex items-center gap-2" data-testid="button-download-report">
              <Download className="h-4 w-4" />
              Download
            </Button>
            <Button onClick={handleSendToDrivers} variant="outline" className="flex items-center gap-2" data-testid="button-send-report">
              <Send className="h-4 w-4" />
              Send to Drivers
            </Button>
            <Button onClick={() => refetch()} variant="ghost" data-testid="button-refresh-report">
              Refresh Data
            </Button>
          </div>

          {/* Printable Report Content */}
          <div id="printable-report" className="space-y-6 bg-white">
            {/* Header */}
            <div className="text-center border-b pb-4">
              <h1 className="text-2xl font-bold text-slate-900">Quarterly Performance Report</h1>
              <p className="text-slate-600 mt-1">
                {new Date().toLocaleDateString()} - {reportData.reportTime}
              </p>
            </div>

            {/* Summary Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-slate-600">Van Drivers</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{reportData.summary.totalVanDrivers}</div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-slate-600">Inventory Drivers</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{reportData.summary.totalInventoryDrivers}</div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-slate-600">Avg MPH</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{reportData.summary.avgMPH}</div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-slate-600">Total Moves</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{reportData.summary.totalMoves}</div>
                </CardContent>
              </Card>
            </div>

            {/* Van Drivers Table */}
            <div>
              <h3 className="text-lg font-bold flex items-center gap-2 mb-3 text-slate-900">
                <Users className="h-5 w-5 text-blue-600" />
                Van Drivers (Sorted by MPH)
              </h3>
              <div className="border rounded-lg overflow-hidden">
                <table className="w-full">
                  <thead className="bg-slate-100">
                    <tr>
                      <th className="text-left p-3 text-sm font-semibold text-slate-700">Rank</th>
                      <th className="text-left p-3 text-sm font-semibold text-slate-700">Driver</th>
                      <th className="text-center p-3 text-sm font-semibold text-slate-700">MPH</th>
                      <th className="text-center p-3 text-sm font-semibold text-slate-700">Units Moved</th>
                      <th className="text-center p-3 text-sm font-semibold text-slate-700">Performance</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.vanDrivers.map((driver: any, index: number) => (
                      <tr key={driver.driverNumber} className="border-t hover:bg-slate-50">
                        <td className="p-3">
                          <Badge variant={index === 0 ? "default" : "outline"}>
                            #{index + 1}
                          </Badge>
                        </td>
                        <td className="p-3 font-medium">{driver.name || `Driver ${driver.driverNumber}`}</td>
                        <td className="p-3 text-center">
                          <span className={`font-bold ${driver.mph >= 4.5 ? 'text-green-600' : 'text-yellow-600'}`}>
                            {driver.mph.toFixed(1)}
                          </span>
                        </td>
                        <td className="p-3 text-center font-semibold">{driver.totalMoves}</td>
                        <td className="p-3 text-center">
                          {driver.mph >= 4.5 ? (
                            <TrendingUp className="h-5 w-5 text-green-600 mx-auto" />
                          ) : (
                            <TrendingDown className="h-5 w-5 text-yellow-600 mx-auto" />
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Inventory Drivers Table */}
            <div>
              <h3 className="text-lg font-bold flex items-center gap-2 mb-3 text-slate-900">
                <Package className="h-5 w-5 text-purple-600" />
                Inventory Drivers (Sorted by Units)
              </h3>
              <div className="border rounded-lg overflow-hidden">
                <table className="w-full">
                  <thead className="bg-slate-100">
                    <tr>
                      <th className="text-left p-3 text-sm font-semibold text-slate-700">Rank</th>
                      <th className="text-left p-3 text-sm font-semibold text-slate-700">Driver</th>
                      <th className="text-center p-3 text-sm font-semibold text-slate-700">Units Processed</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.inventoryDrivers.map((driver: any, index: number) => (
                      <tr key={driver.driverNumber} className="border-t hover:bg-slate-50">
                        <td className="p-3">
                          <Badge variant={index === 0 ? "default" : "outline"}>
                            #{index + 1}
                          </Badge>
                        </td>
                        <td className="p-3 font-medium">{driver.name || `Driver ${driver.driverNumber}`}</td>
                        <td className="p-3 text-center font-semibold">{driver.totalMoves}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Footer */}
            <div className="text-center text-sm text-slate-500 border-t pt-4">
              Generated by Lot Ops Pro • Manheim Nashville
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
